# Introduction {#introduction}

\chaptermark{Introduction}
\minitoc

\noindent In many applications, such as environmental science and finance, we are interested in analysing the tail behaviour of a multivariate random variable in order to assess the risk of certain extreme events^[The code for this project is available at [https://github.com/pawleymatthew/TFR](https://github.com/pawleymatthew/TFR).]. This calls for a multivariate analysis using tools from multivariate extreme value theory, central to which is the notion of extremal dependence, i.e.\ the tail dependence between components of a random vector. For example, practitioners need to be aware if several locations are likely to be jointly impacted by heavy rainfall, so that they can take action to mitigate the risk of large-scale flooding. The need to quantify extremal dependence is core to statistical techniques for multivariate extremes, but it is inherently challenging in high-dimensional settings. 

Mathematically speaking, the extremal dependence structure is characterised by a high-dimensional measure, called the angular measure. Estimating distributions in high dimensions is challenging; in the extremes setting it becomes harder still because only a small fraction of the data contains an informative signal for the distributional tail, limiting our effective sample size. Classical techniques, such as semi- or fully-parametric models, are generally too restrictive, suffer the curse of dimensionality, or are computationally infeasible [@gumbelBivariateExponentialDistributions1960; @tawnBivariateExtremeValue1988; @huslerMaximaNormalRandom1989; @wackernagelMultivariateGeostatisticsIntroduction1995; @boldiMixtureModelMultivariate2007; @decarvalhoSpectralDensityRatio2014; @hansonBernsteinPolynomialAngular2017]. Instead, researchers are exploring how tools from statistical learning, such as clustering and principal component analysis (PCA), can be adapted for extremes [@bernardClusteringMaximaSpatial2013; @chautruDimensionReductionMultivariate2015; @cooleyDecompositionsDependenceHighdimensional2019; @fomichovDetectionGroupsConcomitant2020; @janssenKmeansClusteringExtremes2020; @dreesPrincipalComponentAnalysis2021; @rohrbeckSimulatingFloodEvent2021]. These techniques are better-equipped to handle high-dimensional settings. This report comprises a critical review of such methods, with a focus on the framework for extremal PCA developed by @cooleyDecompositionsDependenceHighdimensional2019 and the algorithm for generating hazard event sets proposed by @rohrbeckSimulatingFloodEvent2021. We perform a detailed illustration of these methods using French rainfall data, identify their limitations, and outline directions for future research.

This report is organised as follows: Chapter \@ref(background-theory) reviews the basic theory of extreme value theory within the framework of multivariate regular variation and overviews classical approaches for modelling the angular measure; Chapter \@ref(survey) surveys statistical learning approaches that can handle high-dimensional settings, focussing on clustering and principal components analysis; Chapter \@ref(application-fr-rain) applies some of these methods to French rainfall data; Chapter \@ref(future-work) discusses their limitations and ideas for future research. 

 