`r if(knitr:::is_latex_output()) '\\startappendices'`
`r if(!knitr:::is_latex_output()) '# (APPENDIX) Appendix {-}'` 

# Simulating $d$-variate max-stable Hüsler-Reiss data {#sim-hr}

## Framework and assumptions

The unit sphere on the non-negative orthant $S_+^{d-1}$ can be partitioned into $2^d-1$ subspaces, called faces, given by
\begin{equation}
\mathcal{E}_I = \{\bm{\theta}\in\mathbb{S}_+^{d-1}:\theta_i>0\,\forall i\in I, \, \theta_j=0\,\forall j\notin I\},
(\#eq:unit-sphere-faces)
\end{equation}
for $I\in\mathcal{P}(V)\setminus \emptyset$, where $\mathcal{P}(V)$ is the power set of $V=\{1,\ldots,d\}$. The face $\mathcal{E}_I$ being charged with $H$-mass, i.e. $H(\mathcal{E}_I)>0$, indicates that the group of components $(X_i:i\in I)$ may be concomitantly extreme while the components $(X_i:i\notin I)$ are much smaller. 

We consider the very simple scenario where there exists a partition of the index set such that asymptotic independence is present between groups but not necessarily within groups. Formally, assume there exists $2\leq k\leq d$ and a partition $I_1\cup\cdots\cup I_k = V$ such that the faces $\mathcal{E}_{I_1},\ldots,\mathcal{E}_{I_k}$ form the support of the angular measure. Without loss of generality, assume that all indices in $I_l$ are smaller than those in $I_m$ for all $1\leq l<m\leq k$. Then the faces $\mathcal{E}_{I_1},\ldots,\mathcal{E}_{I_k}$ can be specified simply by providing their dimensions $d_1,\ldots,d_k$, where $d_i=\abs{I_i}$ for $i=1,\ldots,k$. Finally, define face labels $C_1,\ldots,C_d$ such that $C_i=m$ indicates that $i\in I_m$.

The random vector of interest, $\bm{X}$, is taken to have a $d$-variate max-stable Hüsler-Reiss (HR) distribution [@engelkeEstimationHuslerReissDistributions2015]. The dependence structure is parametrised by a conditionally negative definite matrix $\Gamma\in\R^{d\times d}$, called the variogram. The strength of dependence between $X_i$ and $X_j$ is controlled by $\Gamma_{ij}$ via the relation $\chi_{ij}=2\bar{\Phi}(\sqrt{\Gamma_{ij}}/2)$, where $\bar{\Phi}$ is the survival function of the standard normal distribution. The HR distribution captures all levels of dependence, from complete asymptotic dependence for $\Gamma_{ij}=0$ to asymptotic independence for $\Gamma_{ij}\to\infty$.

## Simulation methodology

@fomichovDetectionGroupsConcomitant2020 describe a procedure for generating such data with $k=2$ faces. We extend the algorithm for arbitrary $2\leq k\leq d$ as follows:
\begin{enumerate}
\item Generate a collection of independent random vectors $\bm{h}_1,\ldots,\bm{h}_d\in\R^d$ whose components are independent, identically distributed Pareto random variables with shape parameter 2.5.
\item Fix $L\in\R$ a large constant and $\beta>0$. Generate the variogram by setting
\begin{equation*}
\Gamma_{ij} = \begin{cases}
\frac{\beta}{d}\norm{\bm{h}_i - \bm{h}_j}_2^2, & \text{if $C_i=C_j$} \\
L, & \text{if $C_i\neq C_j$}.
\end{cases}
\end{equation*}
\item Generate samples of $\bm{X}\sim\mathrm{HüslerReiss}(\Gamma)$, e.g.\ using the \texttt{rmstable} function from the \texttt{graphicalExtremes} package in \textsf{R}.
\end{enumerate}

The parameter $\beta$ scales the distribution of the extremal dependence coefficients, thereby controlling the strength of the within-group extremal dependence. Setting $\Gamma_{ij}=L$ enforces asymptotic independence between groups, since $\chi_{ij} = 2\bar{\Phi}(\sqrt{L}/2)\approx 0$.